"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface, Sequelize) {
        await queryInterface.bulkInsert(
            "Fruits",
            [
                // 1-4
                {
                    name: "Apple",
                    origin: "United States",
                    taste: "Sweet, slightly sour",
                    nutrition: "Vitamin C, K, B6; fiber",
                    color: "Red, green, yellow",
                    season: "Autumn",
                    medical:
                        "Boosts immune system, reduces the risk of heart disease",
                    star: 5.0,
                },
                {
                    name: "Banana",
                    origin: "Philippines",
                    taste: "Sweet",
                    nutrition: "Vitamin C, B6; potassium, magnesium",
                    color: "Yellow",
                    season: "Year-round",
                    medical: "Provides energy, reduces stress",
                    star: 5.0,
                },
                {
                    name: "Bean",
                    origin: "Brazil",
                    taste: "Sweet, fatty",
                    nutrition: "Protein, fiber, vitamin B",
                    color: "Green, yellow, black",
                    season: "Spring, summer",
                    medical: "Supports digestion, provides energy",
                    star: 5.0,
                },
                {
                    name: "Bitter Gourd",
                    origin: "India",
                    taste: "Bitter",
                    nutrition: "Vitamin C, A; fiber",
                    color: "Green",
                    season: "Year-round",
                    medical: "Reduces blood sugar, boosts immune system",
                    star: 5.0,
                },
                // 5-8
                {
                    name: "Bottle Gourd",
                    origin: "India",
                    taste: "Mild",
                    nutrition: "Vitamin C, B; fiber",
                    color: "Green",
                    season: "Year-round",
                    medical: "Weight loss, good for digestion",
                    star: 5.0,
                },
                {
                    name: "Brinjal",
                    origin: "India",
                    taste: "Sweet, aromatic",
                    nutrition: "Folate, potassium, vitamin C",
                    color: "Purple, white, black",
                    season: "Spring, summer",
                    medical:
                        "Supports digestion, reduces the risk of heart disease",
                    star: 4.5,
                },
                {
                    name: "Broccoli",
                    origin: "Italy",
                    taste: "Sweet, slightly spicy",
                    nutrition: "Vitamin C, K; fiber",
                    color: "Green",
                    season: "Winter",
                    medical: "Anti-cancer, protects the heart",
                    star: 4.8,
                },
                {
                    name: "Cabbage",
                    origin: "China",
                    taste: "Sweet, crisp",
                    nutrition: "Vitamin C, K; fiber",
                    color: "Green",
                    season: "Year-round",
                    medical: "Antibacterial, weight loss",
                    star: 4.7,
                },
                // 9-12
                {
                    name: "Capsicum",
                    origin: "Mexico",
                    taste: "Sweet, mildly spicy",
                    nutrition: "Vitamin C, A; fiber",
                    color: "Red, yellow, green",
                    season: "Year-round",
                    medical: "Boosts immune system, antioxidant",
                    star: 4.9,
                },
                {
                    name: "Carrots",
                    origin: "Netherlands",
                    taste: "Sweet",
                    nutrition: "Vitamin A, K; fiber",
                    color: "Red, orange, yellow",
                    season: "Year-round",
                    medical: "Protects vision, reduces cancer risk",
                    star: 4.6,
                },
                {
                    name: "Cauliflower",
                    origin: "Italy",
                    taste: "Sweet, crisp",
                    nutrition: "Vitamin C, K; fiber",
                    color: "White",
                    season: "Winter",
                    medical: "Reduces cancer risk, provides energy",
                    star: 4.8,
                },
                {
                    name: "Chilli",
                    origin: "Mexico",
                    taste: "Spicy",
                    nutrition: "Vitamin C, A; capsaicin",
                    color: "Red, green",
                    season: "Year-round",
                    medical: "Enhances digestion, reduces pain",
                    star: 4.7,
                },
                //13-16
                {
                    name: "Coconut",
                    origin: "Indonesia",
                    taste: "Sweet",
                    nutrition: "Oil, potassium, manganese",
                    color: "White, green",
                    season: "Year-round",
                    medical: "Good for the heart, skin, and hair",
                    star: 4.9,
                },
                {
                    name: "Cucumber",
                    origin: "Thailand",
                    taste: "Mild",
                    nutrition: "Vitamin K, C; water",
                    color: "Green",
                    season: "Year-round",
                    medical: "Reduces stress, hydrates the body",
                    star: 4.5,
                },
                {
                    name: "Custard Apple",
                    origin: "India",
                    taste: "Sweet",
                    nutrition: "Vitamin C, B; potassium",
                    color: "Green, brown",
                    season: "Year-round",
                    medical: "Boosts immunity, reduces fatigue",
                    star: 4.8,
                },
                {
                    name: "Dates",
                    origin: "Egypt",
                    taste: "Sweet",
                    nutrition: "Vitamin B, potassium, magnesium",
                    color: "Brown",
                    season: "Winter",
                    medical: "Boosts energy, good for digestion",
                    star: 4.7,
                },
                //17-20
                {
                    name: "Dragon Fruit",
                    origin: "Thailand",
                    taste: "Sweet, crunchy",
                    nutrition: "Vitamin C, B; fiber",
                    color: "Pink, green",
                    season: "Year-round",
                    medical: "Cell protection, reduces the risk of diabetes",
                    star: 4.8,
                },
                {
                    name: "Egg",
                    origin: "United States",
                    taste: "Sweet, fatty",
                    nutrition: "Protein, vitamin B, D",
                    color: "White, yellow",
                    season: "Year-round",
                    medical: "Builds muscles, enhances brain function",
                    star: 4.6,
                },
                {
                    name: "Garlic",
                    origin: "China",
                    taste: "Spicy, aromatic",
                    nutrition: "Vitamin C, B6; minerals",
                    color: "White",
                    season: "Year-round",
                    medical: "Antibacterial, reduces blood cholesterol",
                    star: 4.9,
                },
                {
                    name: "Grape",
                    origin: "France",
                    taste: "Sweet",
                    nutrition: "Vitamin C, K; fiber",
                    color: "Green, red, black",
                    season: "Summer",
                    medical: "Protects the heart, antioxidant",
                    star: 4.7,
                },
                // 21-24
                {
                    name: "Green Lemon",
                    origin: "Thailand",
                    taste: "Sour",
                    nutrition: "Vitamin C, B; fiber",
                    color: "Green",
                    season: "Year-round",
                    medical: "Weight loss, strengthens the immune system",
                    star: 4.5,
                },
                {
                    name: "Jackfruit",
                    origin: "India",
                    taste: "Sweet, aromatic",
                    nutrition: "Vitamin C, B; potassium",
                    color: "Yellow",
                    season: "Year-round",
                    medical: "Boosts energy, reduces stress",
                    star: 4.7,
                },
                {
                    name: "Kiwi",
                    origin: "New Zealand",
                    taste: "Sweet and sour",
                    nutrition: "Vitamin C, K; fiber",
                    color: "Green, brown",
                    season: "Summer",
                    medical:
                        "Protects the heart, strengthens the immune system",
                    star: 4.6,
                },
                {
                    name: "Mango",
                    origin: "India",
                    taste: "Sweet, sometimes slightly sour",
                    nutrition: "Rich in vitamin C, A, potassium",
                    color: "Varies by type, often yellow or orange",
                    season: "Summer",
                    medical:
                        "May support heart health and boost the immune system",
                    star: 4.9,
                },
                // 25-28
                {
                    name: "Okra",
                    origin: "Various warm climates",
                    taste: "Mild, sweet",
                    nutrition: "Rich in fiber, vitamin C, K, and folate",
                    color: "Green",
                    season: "Year-round",
                    medical:
                        "Contains various pollution-fighting compounds and may help control blood sugar",
                    star: 4.6,
                },
                {
                    name: "Onion",
                    origin: "Grown worldwide, including major producers",
                    taste: "Spicy, can be sweet when ripe",
                    nutrition: "High in vitamin C and fiber",
                    color: "White, red, and yellow",
                    season: "Year-round",
                    medical:
                        "May reduce the risk of heart disease and certain cancers",
                    star: 4.8,
                },
                {
                    name: "Orange",
                    origin: "Native to Southeast Asia but widely cultivated in various countries",
                    taste: "Sweet, slightly sour",
                    nutrition: "High in vitamin C, A, and potassium",
                    color: "Orange",
                    season: "Winter",
                    medical:
                        "Boosts the immune system and maintains skin health",
                    star: 4.7,
                },
                {
                    name: "Papaya",
                    origin: "Indigenous to southern Mexico but now grown extensively in various countries",
                    taste: "Sweet, slightly sour",
                    nutrition: "High in vitamin C, A, and papain enzyme",
                    color: "Orange, yellow",
                    season: "Year-round",
                    medical:
                        "Supports digestion and contains enzymes beneficial for the stomach",
                    star: 4.9,
                },
                // 29-32
                {
                    name: "Peanut",
                    origin: "Cultivated worldwide",
                    taste: "Sweet, nutty",
                    nutrition: "Good fats, protein, vitamin E",
                    color: "Brown",
                    season: "Year-round",
                    medical: "Provides energy, supports heart health",
                    star: 4.5,
                },
                {
                    name: "Pineapple",
                    origin: "Grown in tropical and subtropical regions",
                    taste: "Sweet, can be slightly tangy",
                    nutrition: "High in vitamin C, manganese, fiber",
                    color: "Yellow, green",
                    season: "Year-round",
                    medical: "Contains bromelain enzyme that aids digestion",
                    star: 4.7,
                },
                {
                    name: "Pomegranate",
                    origin: "Cultivated worldwide",
                    taste: "Sweet, tart",
                    nutrition: "High in vitamin C, K, antioxidants",
                    color: "Red, pink",
                    season: "Fall",
                    medical: "Contains powerful antioxidants",
                    star: 4.8,
                },
                {
                    name: "Potato",
                    origin: "Cultivated worldwide",
                    taste: "Sweet, starchy",
                    nutrition: "High in carbohydrates, vitamin C, B6",
                    color: "Brown, white, yellow",
                    season: "Year-round",
                    medical: "Good source of vitamin C and potassium",
                    star: 4.6,
                },
                // 33-36
                {
                    name: "Pumpkin",
                    origin: "Various regions",
                    taste: "Sweet, fragrant",
                    nutrition: "High in vitamin A, C, potassium",
                    color: "Orange",
                    season: "Fall",
                    medical: "Rich in antioxidants, supports eye health",
                    star: 4.7,
                },
                {
                    name: "Radish",
                    origin: "Widely cultivated",
                    taste: "Can be spicy, crunchy",
                    nutrition: "High in vitamin C, fiber",
                    color: "Red, white",
                    season: "Year-round",
                    medical:
                        "Provides pollution-fighting compounds and supports digestion",
                    star: 4.6,
                },
                {
                    name: "Star Fruit",
                    origin: "Southern Vietnam, especially Bến Tre and Vĩnh Long",
                    taste: "Between sour and sweet, can be slightly tart",
                    nutrition: "High in vitamin C, fiber",
                    color: "Yellow when ripe",
                    season: "Year-round",
                    medical: "May support digestion and reduce stress",
                    star: 4.8,
                },
                {
                    name: "Strawberry",
                    origin: "Cultivated widely in temperate regions",
                    taste: "Sweet, can be slightly tart",
                    nutrition: "High in vitamin C, manganese, fiber",
                    color: "Red",
                    season: "Spring and summer",
                    medical:
                        "Contains many pollution-fighting and anti-cancer compounds",
                    star: 4.9,
                },
                // 37-40
                {
                    name: "Sweet Potato",
                    origin: "Cultivated widely",
                    taste: "Sweet, rich",
                    nutrition: "High in vitamin A, C, fiber",
                    color: "Orange, purple",
                    season: "Year-round",
                    medical: "Good for heart health and blood sugar control",
                    star: 4.8,
                },
                {
                    name: "Tomato",
                    origin: "Cultivated widely",
                    taste: "Sweet, can be tart depending on the type",
                    nutrition: "High in vitamin C, A, potassium, fiber",
                    color: "Red",
                    season: "Year-round",
                    medical:
                        "Contains lycopene, may reduce the risk of certain cancers",
                    star: 4.7,
                },
                {
                    name: "Watermelon",
                    origin: "Southern Vietnam",
                    taste: "Sweet, refreshing",
                    nutrition: "High in vitamin A, C, potassium",
                    color: "Red, pink",
                    season: "Summer",
                    medical: "Hydrates the liver, provides water and minerals",
                    star: 4.9,
                },
                {
                    name: "White Mushroom",
                    origin: "Cultivated widely, found in many regions",
                    taste: "Mild, fragrant",
                    nutrition: "High in protein, fiber, vitamin D",
                    color: "White",
                    season: "Year-round",
                    medical:
                        "Boosts the immune system and supports bone health",
                    star: 4.8,
                },
            ],
            { batchSize: 40 }
        );
    },

    async down(queryInterface, Sequelize) {
        await queryInterface.bulkDelete("Fruits", null, { batchSize: 40 });
    },
};
